name: Deploy1

on:
  workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH kalitni sozlash
              run: |
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                touch ~/.ssh/known_hosts
                ssh-keyscan -H ${{vars.HOST}} >> ~/.ssh/known_hosts
              shell: bash
            
            - name: Serverga loyiha o'zgarishlarini qo'shish
              run: |
                ssh ${{vars.USER}}@${{vars.HOST}} << 'EOF'
                if [ -d Loyihalar ]; then
                  cd Loyihalar/WebSocket-chat-app
                  git pull origin main
                  npm install
                else
                  mkdir Loyihalar
                  cd Loyihalar
                  git clone https://github.com/dovudbekdev/WebSocket-chat-app.git
                  cd WebSocket-chat-app
                  npm install
                  cp .env.example .env
                  echo "======== .env fayl tarkibi ========="
                  cat .env
                  echo "====================================="
                  sed -i 's/^PORT=.*/PORT=4000/' .env
                  echo "==== o'zgargan .env tarkibi ========="
                  cat .env
                  echo "======================================"
                fi
                EOF
              shell: bash

            - name: PM2 orqali serverni restart qilish
              run: |
                ssh ${{vars.USER}}@${{vars.HOST}} << 'EOF'
                if pm2 list | grep -q Chat; then
                  pm2 restart Chat
                else
                  cd ~/Loyihalar/WebSocket-chat-app
                  pm2 start server.js --name Chat
                fi
                EOF